# Generated by Django 5.1.4 on 2024-12-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateField(verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('EURO', 'Euro'), ('PLN', 'Polish Zloty'), ('USD', 'US Dollar')], max_length=4, verbose_name='Devise')),
                ('solde', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6, verbose_name='Solde')),
            ],
        ),
    ]
